apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: frontend
    # a53a4d6a356c54dc2951320467cfa760-228284235.us-west-1.elb.amazonaws.com