version: 2.1
jobs:
  test:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: node --version
  build:
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $docker_user_name
          password: $docker_pass  # context / project UI env-var reference
      #Error calling workflow: 'docker-cred'
#Cannot find a definition for job named docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker-compose -f docker-compose-build.yaml build --parallel 
    
workflows:
  test-deploy:
    jobs:
      - test
  docker-cred:
    jobs:
      - build