version: 2.1
jobs:
  test:
    docker: 
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - run: | 
              docker images
              docker ps 
  build:
    docker:
      - image: cimg/node:14.17.3
        auth:
          username: $docker_user_name
          password: $docker_pass  # context / project UI env-var reference
      #Error calling workflow: 'docker-cred'
#Cannot find a definition for job named docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
              docker-compose -f docker-compose-build.yaml build --parallel 
              docker tag udagram-api-user ${docker_user_name}/udagram-api-user:v1
              docker tag udagram-api-feed ${docker_user_name}/udagram-api-feed:v1
              docker tag udagram-frontend:local ${docker_user_name}/udagram-frontend:v1
              docker tag reverseproxy ${docker_user_name}/reverseproxy:v1

              echo "$docker_user_name" | docker login -u "$docker_user_name" -p "$docker_pass"
              docker push ${docker_user_name}/udagram-api-user:v1
              docker push ${docker_user_name}/udagram-api-feed:v1
              docker push ${docker_user_name}/udagram-frontend:v1
              docker push ${docker_user_name}/reverseproxy:v1
              
workflows:
  test-deploy:
    jobs:
      - test
  docker-cred:
    jobs:
      - build